// apps/teskooano/src/plugins/debug-panel/components/renderer-stats/RendererStats.svelte
<script lang="ts">
  import Card from "@core/components/card/Card.svelte";
  let { drawCalls = 0, triangles = 0 }: { drawCalls: number; triangles: number } = $props();
</script>

<Card variant="fluid">
  {#snippet title()}Renderer Stats{/snippet}
  <table>
    <thead>
      <tr>
        <th>Property</th>
        <th>Value</th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td>Draw Calls</td>
        <td>{drawCalls.toLocaleString()}</td>
      </tr>
      <tr>
        <td>Triangles</td>
        <td>{triangles.toLocaleString()}</td>
      </tr>
    </tbody>
  </table>
</Card>

<style>
  table {
    width: 100%;
    border-collapse: collapse;
  }

  th,
  td {
    padding: 0.25rem 0.5rem;
    text-align: left;
    border-bottom: 1px solid var(--border-color-soft);
  }

  th {
    font-weight: var(--font-weight-bold);
    color: var(--text-color-secondary);
  }

  tbody tr:last-child td {
    border-bottom: none;
  }

  td:last-child {
    text-align: right;
  }
</style>

// apps/teskooano/src/plugins/debug-panel/components/renderer-stats/renderer-stats.component.ts
import "../../../../core/components/card/index.js";

const template = document.createElement("template");
template.innerHTML = `
  <style>
    :host {
      display: block;
    }
    table {
      width: 100%;
      border-collapse: collapse;
    }
    th,
    td {
      padding: 0.25rem 0.5rem;
      text-align: left;
      border-bottom: 1px solid var(--border-color-soft);
    }
    th {
      font-weight: var(--font-weight-bold);
      color: var(--text-color-secondary);
    }
    tbody tr:last-child td {
      border-bottom: none;
    }
    td:last-child {
      text-align: right;
    }
  </style>
  <teskooano-card variant="fluid">
    <span slot="title">Renderer Stats</span>
    <table>
      <thead>
        <tr>
          <th>Property</th>
          <th>Value</th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <td>Draw Calls</td>
          <td id="stat-draw-calls">...</td>
        </tr>
        <tr>
          <td>Triangles</td>
          <td id="stat-triangles">...</td>
        </tr>
      </tbody>
    </table>
  </teskooano-card>
`;

export class RendererStatsComponent extends HTMLElement {
  constructor() {
    super();
    this.attachShadow({ mode: "open" });
    this.shadowRoot!.appendChild(template.content.cloneNode(true));
  }

  public renderStats(stats: { drawCalls: number; triangles: number }): void {
    const safeUpdate = (id: string, value: string | number) => {
      const el = this.shadowRoot?.getElementById(id);
      if (el) el.textContent = String(value);
    };

    safeUpdate("stat-draw-calls", stats.drawCalls.toLocaleString());
    safeUpdate("stat-triangles", stats.triangles.toLocaleString());
  }
}
